# Generated by Django 4.0.4 on 2022-06-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedstudent',
            name='student_id',
        ),
    ]
