# Generated by Django 4.0.4 on 2022-06-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_teacher_phone_number_teacher_teacher_initial'),
        ('admins', '0004_alter_assignedstudent_proposal_id_studentmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedstudent',
            name='proposal_id',
        ),
        migrations.AddField(
            model_name='assignedstudent',
            name='student_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
    ]
