# Generated by Django 4.0.4 on 2022-06-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_teacher_phone_number_teacher_teacher_initial'),
        ('admins', '0006_alter_assignedstudent_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignedStudent',
        ),
    ]
