# Generated by Django 4.0.4 on 2022-06-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_assignedstudent_delete_assignstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='final_status',
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='mid_status',
        ),
        migrations.AddField(
            model_name='assignedstudent',
            name='final_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignedstudent',
            name='mid_status',
            field=models.IntegerField(default=0),
        ),
    ]
