# Generated by Django 4.0.4 on 2022-06-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_remove_studentmark_final_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedstudent',
            name='message_body',
            field=models.TextField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='assignedstudent',
            name='message_title',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
