# Generated by Django 4.0.4 on 2022-05-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid_document', models.CharField(max_length=500)),
                ('mid_video', models.CharField(max_length=500)),
                ('final_document', models.CharField(max_length=500)),
                ('final_video', models.CharField(max_length=500)),
                ('github_link', models.CharField(max_length=500)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='DefenceProposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=70)),
                ('credit_complete', models.IntegerField()),
                ('current_cgpa', models.FloatField()),
                ('working_area', models.CharField(max_length=200)),
                ('defence_type', models.CharField(max_length=70)),
                ('defence_title', models.CharField(max_length=100)),
                ('defence_description', models.CharField(max_length=1000)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
    ]
