# Generated by Django 4.0.4 on 2022-05-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenceproposal',
            name='assigned_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defenceproposal',
            name='defence_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defenceproposal',
            name='defence_description',
            field=models.TextField(),
        ),
    ]
