# Generated by Django 4.0.4 on 2022-05-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_initial',
            field=models.CharField(default='SWE', max_length=100),
        ),
    ]
